using DBService.Base;

namespace DBService.Level25Repository.L2L25_CoilPDO
{
    public class L2L25_CoilPDO : BaseRepositoryModel
	{
		public string Message_Length { get; set; }
		public string Message_Id { get; set; }
		public string Date { get; set; }
		public string Time { get; set; }
		public string Order_No { get; set; }
		public string Plan_No { get; set; }
		public string Out_Coil_ID { get; set; }
		public string In_Coil_ID { get; set; }
		public string Start_Time { get; set; }
		public string Finish_Time { get; set; }
		public string Shift { get; set; }
		public string Team { get; set; }
		public string St_No { get; set; }
		public string Out_Coil_Outer_Diameter { get; set; }
		public string Out_Coil_Inner_Diameter { get; set; }
		public string Out_Coil_Length { get; set; }
		public string Out_Coil_Thick { get; set; }
		public string Out_Coil_Head_C40_Thick { get; set; }
		public string Out_Coil_Mid_C40_Thick { get; set; }
		public string Out_Coil_Tail_C40_Thick { get; set; }
		public string Out_Coil_Head_C25_Thick { get; set; }
		public string Out_Coil_Mid_C25_Thick { get; set; }
		public string Out_Coil_Tail_C25_Thick { get; set; }
		public string Out_Coil_Width { get; set; }
		public string Out_Coil_Act_WT { get; set; }
		public string Out_Coil_Gross_WT { get; set; }
		public string Head_Pass_Num { get; set; }
		public string Mid_Pass_Num { get; set; }
		public string Tail_Pass_Num { get; set; }
		public string Out_Coil_Use_Sleeve_Flag { get; set; }
		public string Out_Sleeve_Diameter { get; set; }
		public string Out_Sleeve_Type_Code { get; set; }
		public string Out_Paper_Req_Code { get; set; }
		public string Out_Paper_Code { get; set; }
		public string Head_Paper_Length { get; set; }
		public string Head_Paper_Width { get; set; }
		public string Tail_Paper_Length { get; set; }
		public string Tail_Paper_Width { get; set; }
		public string D01_Code { get; set; }
		public string D01_Origin { get; set; }
		public string D01_Sid { get; set; }
		public string D01_Pos_W { get; set; }
		public string D01_Pos_L_Start { get; set; }
		public string D01_Pos_L_End { get; set; }
		public string D01_Level { get; set; }
		public string D01_Percent { get; set; }
		public string D01_QGrade { get; set; }
		public string D02_Code { get; set; }
		public string D02_Origin { get; set; }
		public string D02_Sid { get; set; }
		public string D02_Pos_W { get; set; }
		public string D02_Pos_L_Start { get; set; }
		public string D02_Pos_L_End { get; set; }
		public string D02_Level { get; set; }
		public string D02_Percent { get; set; }
		public string D02_QGrade { get; set; }
		public string D03_Code { get; set; }
		public string D03_Origin { get; set; }
		public string D03_Sid { get; set; }
		public string D03_Pos_W { get; set; }
		public string D03_Pos_L_Start { get; set; }
		public string D03_Pos_L_End { get; set; }
		public string D03_Level { get; set; }
		public string D03_Percent { get; set; }
		public string D03_QGrade { get; set; }
		public string D04_Code { get; set; }
		public string D04_Origin { get; set; }
		public string D04_Sid { get; set; }
		public string D04_Pos_W { get; set; }
		public string D04_Pos_L_Start { get; set; }
		public string D04_Pos_L_End { get; set; }
		public string D04_Level { get; set; }
		public string D04_Percent { get; set; }
		public string D04_QGrade { get; set; }
		public string D05_Code { get; set; }
		public string D05_Origin { get; set; }
		public string D05_Sid { get; set; }
		public string D05_Pos_W { get; set; }
		public string D05_Pos_L_Start { get; set; }
		public string D05_Pos_L_End { get; set; }
		public string D05_Level { get; set; }
		public string D05_Percent { get; set; }
		public string D05_QGrade { get; set; }
		public string D06_Code { get; set; }
		public string D06_Origin { get; set; }
		public string D06_Sid { get; set; }
		public string D06_Pos_W { get; set; }
		public string D06_Pos_L_Start { get; set; }
		public string D06_Pos_L_End { get; set; }
		public string D06_Level { get; set; }
		public string D06_Percent { get; set; }
		public string D06_QGrade { get; set; }
		public string D07_Code { get; set; }
		public string D07_Origin { get; set; }
		public string D07_Sid { get; set; }
		public string D07_Pos_W { get; set; }
		public string D07_Pos_L_Start { get; set; }
		public string D07_Pos_L_End { get; set; }
		public string D07_Level { get; set; }
		public string D07_Percent { get; set; }
		public string D07_QGrade { get; set; }
		public string D08_Code { get; set; }
		public string D08_Origin { get; set; }
		public string D08_Sid { get; set; }
		public string D08_Pos_W { get; set; }
		public string D08_Pos_L_Start { get; set; }
		public string D08_Pos_L_End { get; set; }
		public string D08_Level { get; set; }
		public string D08_Percent { get; set; }
		public string D08_QGrade { get; set; }
		public string D09_Code { get; set; }
		public string D09_Origin { get; set; }
		public string D09_Sid { get; set; }
		public string D09_Pos_W { get; set; }
		public string D09_Pos_L_Start { get; set; }
		public string D09_Pos_L_End { get; set; }
		public string D09_Level { get; set; }
		public string D09_Percent { get; set; }
		public string D09_QGrade { get; set; }
		public string D10_Code { get; set; }
		public string D10_Origin { get; set; }
		public string D10_Sid { get; set; }
		public string D10_Pos_W { get; set; }
		public string D10_Pos_L_Start { get; set; }
		public string D10_Pos_L_End { get; set; }
		public string D10_Level { get; set; }
		public string D10_Percent { get; set; }
		public string D10_QGrade { get; set; }
		public string Winding_Dire { get; set; }
		public string Better_Surf_Ward_Code { get; set; }
		public string Hold_Maker { get; set; }
		public string Hold_Flag { get; set; }
		public string Hold_Cause_Code { get; set; }
		public string Sample_Flag { get; set; }
		public string Fixed_Wt_Flag { get; set; }
		public string Final_Coil_Flag { get; set; }
		public string Scrap_Flag { get; set; }
		public string Sample_Pos_Code { get; set; }
		public string Surface_Accu_Code { get; set; }
		public string Head_Hole_Position { get; set; }
		public string Head_Leader_Length { get; set; }
		public string Head_Leader_Width { get; set; }
		public string Head_Leader_Thickness { get; set; }
		public string Tail_Hole_Position { get; set; }
		public string Tail_Leader_Length { get; set; }
		public string Tail_Leader_Width { get; set; }
		public string Tail_Leader_Thickness { get; set; }
		public string Head_Leader_St_No { get; set; }
		public string Tail_Leader_St_No { get; set; }
		public string Head_Off_Gauge { get; set; }
		public string Tail_Off_Gauge { get; set; }
		public string Pre_Grinding_Surface { get; set; }
		public string Grinding_Count_Out { get; set; }
		public string Grinding_Count_In { get; set; }
		public string Appoint_Grinding_Surface { get; set; }
		public string Oil_Flag { get; set; }
		public string Surface_Accu_Code_In { get; set; }
		public string Surface_Accu_Code_Out { get; set; }
		public string Process_Code { get; set; }
        public string Head_Rough { get; set; }
        public string Mid_Rough { get; set; }
        public string Tail_Rough { get; set; }

        public string Head_Rough_Rz { get; set; }
		public string Mid_Rough_Rz { get; set; }
		public string Tail_Rough_Rz { get; set; }
		public string Head_Rough_Rmax { get; set; }
        public string Mid_Rough_Rmax { get; set; }
        public string Tail_Rough_Rmax { get; set; }
        public string Uncoil_Direction { get; set; }
		public string Recoiler_ActTen_Avg { get; set; }
		public int Paper_Wt { get; set; }
		public float Sleeve_Wt { get; set; }
	}
}
