using Core.Define;
using Core.Util;
using DBService.Repository.PDI;
using MsgStruct;
using System;
using System.Security.Cryptography;

namespace MsgConvert.DBTable
{
    public static class PDIEntityFactory
    {
        public static PDIEntity.TBL_PDI ToTblCoilPDI(this MMSL2Rcv.Msg_PDI pdiMsg)
        {
            var tblPDI = new PDIEntity.TBL_PDI
            {
                Is_Dummy_Coil = EventDef.FALSE,
                Plan_No = pdiMsg.Plan_No.ToStr(),
                Mat_Seq_No  = pdiMsg.Mat_Plan_Seq_No.ToStr().ToNullable<int>()??0,
                Plan_Type = pdiMsg.Plan_Type.ToStr(),
                In_Coil_ID = pdiMsg.In_Mat_No.ToStr(),
                In_Coil_Thick = pdiMsg.In_Mat_Thick.ToStr().ToNullable<float>()/1000 ?? 0,
                In_Coil_Width = pdiMsg.In_Mat_Width.ToStr().ToNullable<float>()/10 ?? 0,
                In_Coil_Wt = pdiMsg.In_Mat_Wt.ToStr().ToNullable<int>() ?? 0,
                In_Coil_Length = pdiMsg.In_Mat_Len.ToStr().ToNullable<int>() ?? 0,
                In_Coil_Inner_Diameter = pdiMsg.In_Mat_Inner_Dia.ToStr().ToNullable<int>() ?? 0,
                In_Coil_Outer_Diameter = pdiMsg.In_Mat_Outer_Dia.ToStr().ToNullable<int>() ?? 0,
                In_Paper_Req_Code = pdiMsg.Paper_Req_Code.ToStr(),
                In_Paper_Code = pdiMsg.Paper_Code.ToStr(),
                Head_Paper_Length = pdiMsg.Head_Paper_Length.ToStr().ToNullable<int>() ?? 0,
                Head_Paper_Width = pdiMsg.Head_Paper_Width.ToStr().ToNullable<float>()/10 ?? 0,
                Tail_Paper_Length = pdiMsg.Tail_Paper_Length.ToStr().ToNullable<int>() ?? 0,
                Tail_Paper_Width = pdiMsg.Tail_Paper_Width.ToStr().ToNullable<float>()/ 10 ?? 0,
                In_Sleeve_Type_Code = pdiMsg.Sleeve_Type_Code.ToStr(),
                In_Sleeve_Diameter = pdiMsg.Sleeve_Diamter.ToStr().ToNullable<int>() ?? 0,
                St_No = pdiMsg.St_No.ToStr(),
                Density = pdiMsg.Density.ToStr().ToNullable<float>() ?? 0,
                Surface_Accuracy_Acture = pdiMsg.Surface_Accuracy.ToStr(),
                Surface_Accu_Code_Order = pdiMsg.Surface_Accu_Code.ToStr(),
                Flatness_Avg_CR = pdiMsg.Flatness_Avg_Cr.ToStr().ToNullable<int>() ?? 0,
                Better_Surf_Ward_Code = pdiMsg.Better_Surf_Ward_Code.ToStr(),
                Uncoil_Direction = pdiMsg.Uncoil_Direction.ToStr(),
                Origin_Code = pdiMsg.Origin_Code.ToStr(),
                Pack_Mode = pdiMsg.Pack_Mode.ToStr().ToNullable<int>() ?? 0,
                Out_Paper_Req_Code = pdiMsg.Out_Paper_Req_Code.ToStr(),
                Out_Paper_Code = pdiMsg.Out_Paper_Code.ToStr(),
                Out_Sleeve_Type_Code = pdiMsg.Out_Sleeve_Type_Code.ToStr(),
                Out_Sleeve_Diamter = pdiMsg.Out_Sleeve_Diamter.ToStr().ToNullable<int>() ?? 0,
                Out_Coil_ID = pdiMsg.Out_Mat_No.ToStr(),
                Order_No = pdiMsg.Order_No.ToStr(),
                Order_Cust_Code = pdiMsg.Order_Cust_Code.ToStr(),
                Prev_Whole_Backlog_Code = pdiMsg.Prev_Whole_Backlog_Code.ToStr(),
                Next_Whole_Backlog_Code = pdiMsg.Next_Whole_Backlog_Code.ToStr(),
                Head_Leader_Attached = pdiMsg.Head_Leader_Accached.ToStr(),
                Head_Hole_Position = pdiMsg.Head_Hole_Position.ToStr().ToNullable<float>()/1000 ?? 0,
                Head_Leader_Thickness = pdiMsg.Head_Leader_Thick.ToStr().ToNullable<float>()/1000 ?? 0,
                Head_Leader_Width = pdiMsg.Head_Leader_Width.ToStr().ToNullable<float>()/10 ?? 0,
                Head_Leader_Length = pdiMsg.Head_Leader_Length.ToStr().ToNullable<int>() ?? 0,
                Tail_Leader_Attached = pdiMsg.Tail_Leader_Accached.ToStr(),
                Tail_Hole_Position = pdiMsg.Tail_Hole_Position.ToStr().ToNullable<float>()/1000 ?? 0,
                Tail_Leader_Thickness = pdiMsg.Tail_Leader_Thick.ToStr().ToNullable<float>()/1000 ?? 0,
                Tail_Leader_Width = pdiMsg.Tail_Leader_Width.ToStr().ToNullable<float>()/10 ?? 0,
                Tail_Leader_Length = pdiMsg.Tail_Leader_Length.ToStr().ToNullable<int>() ?? 0,
                Head_Leader_St_No = pdiMsg.Head_Leader_St_No.ToStr(),
                Tail_Leader_St_No = pdiMsg.Tail_Leader_St_No.ToStr(),
                Out_Coil_Thick = pdiMsg.Out_Mat_Thick.ToStr().ToNullable<float>()/1000 ?? 0,
                Out_Coil_Thick_Min = pdiMsg.Out_Mat_Min_Thick.ToStr().ToNullable<float>()/1000 ?? 0,
                Out_Coil_Thick_Max = pdiMsg.Out_Mat_Max_Thick.ToStr().ToNullable<float>()/1000 ?? 0,
                Out_Coil_Width = pdiMsg.Out_Mat_Width.ToStr().ToNullable<float>()/10 ?? 0,
                Out_Coil_Inner_Diameter = pdiMsg.Out_Mat_Inner_Dia.ToStr().ToNullable<int>() ?? 0,
                Grind_Flag = pdiMsg.Grinding_Flag.ToStr(),
                Pack_Type_Code = pdiMsg.Pack_Type_Code.ToStr(),
                Repair_Type = pdiMsg.Repair_Type.ToStr(),
                D01_Code = pdiMsg.D1_Code.ToStr(),
                D01_Origin = pdiMsg.D1_Origin.ToStr(),
                D01_Sid = pdiMsg.D1_Sid.ToStr(),
                D01_Pos_W = pdiMsg.D1_Pos_W.ToStr(),
                D01_Pos_L_Start = pdiMsg.D1_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D01_Pos_L_End = pdiMsg.D1_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D01_Level = pdiMsg.D1_Level.ToStr(),
                D01_Percent = pdiMsg.D1_Percent.ToStr().ToNullable<int>() ?? 0,
                D01_QGrade = pdiMsg.D1_QGrade.ToStr(),
                D02_Code = pdiMsg.D2_Code.ToStr(),
                D02_Origin = pdiMsg.D2_Origin.ToStr(),
                D02_Sid = pdiMsg.D2_Sid.ToStr(),
                D02_Pos_W = pdiMsg.D2_Pos_W.ToStr(),
                D02_Pos_L_Start = pdiMsg.D2_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D02_Pos_L_End = pdiMsg.D2_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D02_Level = pdiMsg.D2_Level.ToStr(),
                D02_Percent = pdiMsg.D2_Percent.ToStr().ToNullable<int>() ?? 0,
                D02_QGrade = pdiMsg.D2_QGrade.ToStr(),
                D03_Code = pdiMsg.D3_Code.ToStr(),
                D03_Origin = pdiMsg.D3_Origin.ToStr(),
                D03_Sid = pdiMsg.D3_Sid.ToStr(),
                D03_Pos_W = pdiMsg.D3_Pos_W.ToStr(),
                D03_Pos_L_Start = pdiMsg.D3_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D03_Pos_L_End = pdiMsg.D3_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D03_Level = pdiMsg.D3_Level.ToStr(),
                D03_Percent = pdiMsg.D3_Percent.ToStr().ToNullable<int>() ?? 0,
                D03_QGrade = pdiMsg.D3_QGrade.ToStr(),
                D04_Code = pdiMsg.D4_Code.ToStr(),
                D04_Origin = pdiMsg.D4_Origin.ToStr(),
                D04_Sid = pdiMsg.D4_Sid.ToStr(),
                D04_Pos_W = pdiMsg.D4_Pos_W.ToStr(),
                D04_Pos_L_Start = pdiMsg.D4_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D04_Pos_L_End = pdiMsg.D4_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D04_Level = pdiMsg.D4_Level.ToStr(),
                D04_Percent = pdiMsg.D4_Percent.ToStr().ToNullable<int>() ?? 0,
                D04_QGrade = pdiMsg.D4_QGrade.ToStr(),
                D05_Code = pdiMsg.D5_Code.ToStr(),
                D05_Origin = pdiMsg.D5_Origin.ToStr(),
                D05_Sid = pdiMsg.D5_Sid.ToStr(),
                D05_Pos_W = pdiMsg.D5_Pos_W.ToStr(),
                D05_Pos_L_Start = pdiMsg.D5_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D05_Pos_L_End = pdiMsg.D5_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D05_Level = pdiMsg.D5_Level.ToStr(),
                D05_Percent = pdiMsg.D5_Percent.ToStr().ToNullable<int>() ?? 0,
                D05_QGrade = pdiMsg.D5_QGrade.ToStr(),
                D06_Code = pdiMsg.D6_Code.ToStr(),
                D06_Origin = pdiMsg.D6_Origin.ToStr(),
                D06_Sid = pdiMsg.D6_Sid.ToStr(),
                D06_Pos_W = pdiMsg.D6_Pos_W.ToStr(),
                D06_Pos_L_Start = pdiMsg.D6_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D06_Pos_L_End = pdiMsg.D6_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D06_Level = pdiMsg.D6_Level.ToStr(),
                D06_Percent = pdiMsg.D6_Percent.ToStr().ToNullable<int>() ?? 0,
                D06_QGrade = pdiMsg.D6_QGrade.ToStr(),
                D07_Code = pdiMsg.D7_Code.ToStr(),
                D07_Origin = pdiMsg.D7_Origin.ToStr(),
                D07_Sid = pdiMsg.D7_Sid.ToStr(),
                D07_Pos_W = pdiMsg.D7_Pos_W.ToStr(),
                D07_Pos_L_Start = pdiMsg.D7_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D07_Pos_L_End = pdiMsg.D7_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D07_Level = pdiMsg.D7_Level.ToStr(),
                D07_Percent = pdiMsg.D7_Percent.ToStr().ToNullable<int>() ?? 0,
                D07_QGrade = pdiMsg.D7_QGrade.ToStr(),
                D08_Code = pdiMsg.D8_Code.ToStr(),
                D08_Origin = pdiMsg.D8_Origin.ToStr(),
                D08_Sid = pdiMsg.D8_Sid.ToStr(),
                D08_Pos_W = pdiMsg.D8_Pos_W.ToStr(),
                D08_Pos_L_Start = pdiMsg.D8_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D08_Pos_L_End = pdiMsg.D8_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D08_Level = pdiMsg.D8_Level.ToStr(),
                D08_Percent = pdiMsg.D8_Percent.ToStr().ToNullable<int>() ?? 0,
                D08_QGrade = pdiMsg.D8_QGrade.ToStr(),
                D09_Code = pdiMsg.D9_Code.ToStr(),
                D09_Origin = pdiMsg.D9_Origin.ToStr(),
                D09_Sid = pdiMsg.D9_Sid.ToStr(),
                D09_Pos_W = pdiMsg.D9_Pos_W.ToStr(),
                D09_Pos_L_Start = pdiMsg.D9_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D09_Pos_L_End = pdiMsg.D9_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D09_Level = pdiMsg.D9_Level.ToStr(),
                D09_Percent = pdiMsg.D9_Percent.ToStr().ToNullable<int>() ?? 0,
                D09_QGrade = pdiMsg.D9_QGrade.ToStr(),
                D10_Code = pdiMsg.D10_Code.ToStr(),
                D10_Origin = pdiMsg.D10_Origin.ToStr(),
                D10_Sid = pdiMsg.D10_Sid.ToStr(),
                D10_Pos_W = pdiMsg.D10_Pos_W.ToStr(),
                D10_Pos_L_Start = pdiMsg.D10_Pos_L_Start.ToStr().ToNullable<int>() ?? 0,
                D10_Pos_L_End = pdiMsg.D10_Pos_L_End.ToStr().ToNullable<int>() ?? 0,
                D10_Level = pdiMsg.D10_Level.ToStr(),
                D10_Percent = pdiMsg.D10_Percent.ToStr().ToNullable<int>() ?? 0,
                D10_QGrade = pdiMsg.D10_QGrade.ToStr(),
                Test_Plan_No = pdiMsg.Test_Plan_No.ToStr(),
                Qc_Rmark = pdiMsg.Qc_Rmark.ToStr(),
                Head_Off_Gauge = pdiMsg.Head_Off_Gauge.ToStr().ToNullable<int>() ?? 0,
                Tail_Off_Gauge = pdiMsg.Tail_Off_Gauge.ToStr().ToNullable<int>() ?? 0,
                Pre_Grinding_Surface = pdiMsg.Pre_Grinding_Surface.ToStr(),
                Grinding_Count_Out = pdiMsg.Grinding_Count_Out.ToStr().ToNullable<int>() ?? 0,
                Grinding_Count_In = pdiMsg.Grinding_Count_In.ToStr().ToNullable<int>() ?? 0,
                Appoint_Grinding_Surface = pdiMsg.Appoint_Grinding_Surface.ToStr(),
                Surface_Accu_Code_In = pdiMsg.Surface_Accu_Code_In.ToStr(),
                Surface_Accu_Code_Out = pdiMsg.Surface_Accu_Code_Out.ToStr(),
                Repair_Remark = pdiMsg.Repair_Remark.ToStr(),
                Skim_Flag = pdiMsg.Skim_Flag.ToStr(),
                Polishing_Type = pdiMsg.Polishing_Type.ToStr(),
                Sg_Sign = pdiMsg.Sg_Sign.ToStr(),
                Process_Code = pdiMsg.Process_Code.ToStr(),
                Ys_Stand = pdiMsg.Ys_Stand.ToStr().ToNullable<float>() ?? 0,
                Ys_Max = pdiMsg.Ys_Max.ToStr().ToNullable<float>() ?? 0,
                Ys_Min = pdiMsg.Ys_Min.ToStr().ToNullable<float>() ?? 0,
                Order_Cust_Ename = pdiMsg.Order_Cust_Ename.ToStr(),
                Order_Cust_Cname = pdiMsg.Order_Cust_Cname.ToStr(),
                Surface_Accu_Desc_Order = pdiMsg.Surface_Accu_Desc.ToStr(),
                Surface_Accuracy_Desc_Acture = pdiMsg.Surface_Accuracy_Desc.ToStr(),
                Surface_Accu_Desc_In = pdiMsg.Surface_Accu_Desc_In.ToStr(),
                Surface_Accu_Desc_Out = pdiMsg.Surface_Accu_Desc_Out.ToStr(),
               
            };

            tblPDI.StripYieldStress = (int)(tblPDI.Ys_Max + tblPDI.Ys_Min) / 2;

            return tblPDI;
        }
        public static PDIEntity.TBL_PDI ToTblCoilPDI(this MMSL2Rcv.Msg_Dummy_Coil_List messagePdi)
        {
            var tblPDI = new PDIEntity.TBL_PDI
            {
                Plan_No = "D"+ MD5.Create().GetMd5Hash(Guid.NewGuid().ToString()).Truncate(9),
                Mat_Seq_No  = MD5.Create().GetMd5Hash(Guid.NewGuid().ToString()).Truncate(3).ToNullable<int>()??0,

                Is_Dummy_Coil = EventDef.TRUE,
                In_Coil_ID = messagePdi.CoilNoID,
                In_Coil_Thick = messagePdi.DummyCoilThick.ToNullable<float>()/1000 ?? 0,
                In_Coil_Width = messagePdi.DummyCoilWidth.ToNullable<float>()/10 ?? 0,
                In_Coil_Wt = messagePdi.DummyCoilWeight.ToNullable<int>() ?? 0,
                In_Coil_Length = messagePdi.DummyCoilLength.ToNullable<int>() ?? 0,
                In_Coil_Inner_Diameter = messagePdi.DummyCoilInner.ToNullable<int>() ?? 0,
                In_Coil_Outer_Diameter = messagePdi.DummyCoilDiam.ToNullable<int>() ?? 0,
                Density = messagePdi.Density.ToNullable<float>()  ?? 0,
                St_No = messagePdi.GradeCode,
                Sg_Sign = messagePdi.GradeSign,
                Out_Coil_ID = messagePdi.CoilNoID
            };

            return tblPDI;
        }
    }
}
