using DBService.Base;

namespace DBService.Level25Repository.L2L25_CoilPDI
{
    public class L2L25_CoilPDI : BaseRepositoryModel
    {
		public string Message_Length { get; set; }
		public string Message_Id { get; set; }
		public string Date { get; set; }
		public string Time { get; set; }
		public string Plan_No { get; set; }
		public string Mat_Seq_No { get; set; }
		public string Plan_Type { get; set; }
		public string In_Coil_ID { get; set; }
		public string In_Coil_Thick { get; set; }
		public string In_Coil_Width { get; set; }
		public string In_Coil_Wt { get; set; }
		public string In_Coil_Length { get; set; }
		public string In_Coil_Inner_Diameter { get; set; }
		public string In_Coil_Outer_Diameter { get; set; }
		public string In_Paper_Req_Code { get; set; }
		public string In_Paper_Code { get; set; }
		public string Head_Paper_Length { get; set; }
		public string Head_Paper_Width { get; set; }
		public string Tail_Paper_Length { get; set; }
		public string Tail_Paper_Width { get; set; }
		public string In_Sleeve_Type_Code { get; set; }
		public string In_Sleeve_Diameter { get; set; }
		public string St_No { get; set; }
		public string Density { get; set; }
		public string Surface_Accuracy_Acture { get; set; }
		public string Surface_Accu_Code_Order { get; set; }
		public string Flatness_Avg_CR { get; set; }
		public string Better_Surf_Ward_Code { get; set; }
		public string UnCoil_Direction { get; set; }
		public string Origin_Code { get; set; }
		public string Pack_Mode { get; set; }
		public string Out_Paper_Req_Code { get; set; }
		public string Out_Paper_Code { get; set; }
		public string Out_Sleeve_Type_Code { get; set; }
		public string Out_Sleeve_Diamter { get; set; }
		public string Out_Coil_ID { get; set; }
		public string Order_No { get; set; }
		public string Order_Cust_Code { get; set; }
		public string Prev_Whole_Backlog_Code { get; set; }
		public string Next_Whole_Backlog_Code { get; set; }
		public string Head_Leader_Attached { get; set; }
		public string Head_Hole_Position { get; set; }
		public string Head_Leader_Thickness { get; set; }
		public string Head_Leader_Width { get; set; }
		public string Head_Leader_Length { get; set; }
		public string Tail_Leader_Attached { get; set; }
		public string Tail_Hole_Position { get; set; }
		public string Tail_Leader_Thickness { get; set; }
		public string Tail_Leader_Width { get; set; }
		public string Tail_Leader_Length { get; set; }
		public string Head_Leader_St_No { get; set; }
		public string Tail_Leader_St_No { get; set; }
		public string Out_Coil_Thick { get; set; }
		public string Out_Coil_Thick_Min { get; set; }
		public string Out_Coil_Thick_Max { get; set; }
		public string Out_Coil_Width { get; set; }
		public string Out_Coil_Inner_Diameter { get; set; }
		public string Grind_Flag { get; set; }
		public string Pack_Type_Code { get; set; }
		public string Repair_Type { get; set; }
		public string D01_Code { get; set; }
		public string D01_Origin { get; set; }
		public string D01_Sid { get; set; }
		public string D01_Pos_W { get; set; }
		public string D01_Pos_L_Start { get; set; }
		public string D01_Pos_L_End { get; set; }
		public string D01_Level { get; set; }
		public string D01_Percent { get; set; }
		public string D01_QGrade { get; set; }
		public string D02_Code { get; set; }
		public string D02_Origin { get; set; }
		public string D02_Sid { get; set; }
		public string D02_Pos_W { get; set; }
		public string D02_Pos_L_Start { get; set; }
		public string D02_Pos_L_End { get; set; }
		public string D02_Level { get; set; }
		public string D02_Percent { get; set; }
		public string D02_QGrade { get; set; }
		public string D03_Code { get; set; }
		public string D03_Origin { get; set; }
		public string D03_Sid { get; set; }
		public string D03_Pos_W { get; set; }
		public string D03_Pos_L_Start { get; set; }
		public string D03_Pos_L_End { get; set; }
		public string D03_Level { get; set; }
		public string D03_Percent { get; set; }
		public string D03_QGrade { get; set; }
		public string D04_Code { get; set; }
		public string D04_Origin { get; set; }
		public string D04_Sid { get; set; }
		public string D04_Pos_W { get; set; }
		public string D04_Pos_L_Start { get; set; }
		public string D04_Pos_L_End { get; set; }
		public string D04_Level { get; set; }
		public string D04_Percent { get; set; }
		public string D04_QGrade { get; set; }
		public string D05_Code { get; set; }
		public string D05_Origin { get; set; }
		public string D05_Sid { get; set; }
		public string D05_Pos_W { get; set; }
		public string D05_Pos_L_Start { get; set; }
		public string D05_Pos_L_End { get; set; }
		public string D05_Level { get; set; }
		public string D05_Percent { get; set; }
		public string D05_QGrade { get; set; }
		public string D06_Code { get; set; }
		public string D06_Origin { get; set; }
		public string D06_Sid { get; set; }
		public string D06_Pos_W { get; set; }
		public string D06_Pos_L_Start { get; set; }
		public string D06_Pos_L_End { get; set; }
		public string D06_Level { get; set; }
		public string D06_Percent { get; set; }
		public string D06_QGrade { get; set; }
		public string D07_Code { get; set; }
		public string D07_Origin { get; set; }
		public string D07_Sid { get; set; }
		public string D07_Pos_W { get; set; }
		public string D07_Pos_L_Start { get; set; }
		public string D07_Pos_L_End { get; set; }
		public string D07_Level { get; set; }
		public string D07_Percent { get; set; }
		public string D07_QGrade { get; set; }
		public string D08_Code { get; set; }
		public string D08_Origin { get; set; }
		public string D08_Sid { get; set; }
		public string D08_Pos_W { get; set; }
		public string D08_Pos_L_Start { get; set; }
		public string D08_Pos_L_End { get; set; }
		public string D08_Level { get; set; }
		public string D08_Percent { get; set; }
		public string D08_QGrade { get; set; }
		public string D09_Code { get; set; }
		public string D09_Origin { get; set; }
		public string D09_Sid { get; set; }
		public string D09_Pos_W { get; set; }
		public string D09_Pos_L_Start { get; set; }
		public string D09_Pos_L_End { get; set; }
		public string D09_Level { get; set; }
		public string D09_Percent { get; set; }
		public string D09_QGrade { get; set; }
		public string D10_Code { get; set; }
		public string D10_Origin { get; set; }
		public string D10_Sid { get; set; }
		public string D10_Pos_W { get; set; }
		public string D10_Pos_L_Start { get; set; }
		public string D10_Pos_L_End { get; set; }
		public string D10_Level { get; set; }
		public string D10_Percent { get; set; }
		public string D10_QGrade { get; set; }
		public string Test_Plan_No { get; set; }
		public string Qc_Rmark { get; set; }
		public string Head_Off_Gauge { get; set; }
		public string Tail_Off_Gauge { get; set; }
		public string Pre_Grinding_Surface { get; set; }
		public string Grinding_Count_Out { get; set; }
		public string Grinding_Count_In { get; set; }
		public string Appoint_Grinding_Surface { get; set; }
		public string Surface_Accu_Code_In { get; set; }
		public string Surface_Accu_Code_Out { get; set; }
		public string Repair_Remark { get; set; }
		public string Skim_Flag { get; set; }
		public string Polishing_Type { get; set; }
		public string Sg_Sign { get; set; }
		public string Process_Code { get; set; }
		public string Ys_Stand { get; set; }
		public string Ys_Max { get; set; }
		public string Ys_Min { get; set; }
		public string Order_Cust_EName { get; set; }
		public string Order_Cust_CName { get; set; }
		public string Surface_Accu_Desc_Order { get; set; }
		public string Surface_Accuracy_Desc_Acture { get; set; }
		public string Surface_Accu_Desc_In { get; set; }
		public string Surface_Accu_Desc_Out { get; set; }
	}
}
