using DBService.Base;
using System;
using static DBService.Base.DBAttributes;

namespace DBService.L1Repository
{
    public class L2L1MsgDBModel
    {
        public class L2L1_202 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public DateTime DateTime { get; set; }
            [PrimaryKey]
            public string CoilId { get; set; }
            public string SteelGrade { get; set; }
            public short CoilThickness { get; set; }
            public short CoilWidth { get; set; }
            public short CoilLength { get; set; }
            public short CoilinnerDiameter { get; set; }
            public short CoilouterDiameter { get; set; }
            public short SleeveInstallledCoil { get; set; }
            public short SleeveOuterDiameter { get; set; }
            public short PaperInstalledCoil { get; set; }
            public short IncomingCoilwoundDirection { get; set; }
            public short ProcessingSurface { get; set; }
            public short CoilTuning { get; set; }
            public short HeadEndLeaderAttached { get; set; }
            public short TailEndLeaderAttached { get; set; }
            public string TestPlanNo { get; set; }

            public short PresetPosition { get; set; }
            [PrimaryKey]
            public override DateTime CreateTime { get; set; }
        }

        public class L2L1_203 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public System.DateTime DateTime { get; set; }
            public short CoilIDConfirmResult { get; set; }
            [PrimaryKey]
            public override DateTime CreateTime { get; set; }
        }

        public class L2L1_204 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public System.DateTime DateTime { get; set; }
            public int PresetPosition { get; set; }
            public string TestPlanNo { get; set; }
            public string CoilId { get; set; }
            public float Density { get; set; }
            public string SteelGrade { get; set; }
            public short CoilLength { get; set; }
            public short CoilThickness { get; set; }
            public short CoilWidth { get; set; }
            public short CoilInnerDiameter { get; set; }
            public short CoilOuterDiameter { get; set; }
            public short SleeveInstallledCoil { get; set; }
            public short SleeveOuterDiameter { get; set; }
            public short PaperInstalledCoil { get; set; }
            public short CoilPaperCode { get; set; }
            public short CoilPaperType { get; set; }
            public short OffGaugeHead { get; set; }
            public short OffGaugeTail { get; set; }
            public short FlattenerIntermesh1 { get; set; }
            public short FlattenerIntermesh2 { get; set; }
            public short DegreasingFlag { get; set; }
            public short IncomingCoilWoundDirection { get; set; }
            public short ProcessingSurface { get; set; }
            public short CoilTurning { get; set; }
            public short HeadEndLeaderAttached { get; set; }
            public short HeadEndLeaderSteelGrade { get; set; }
            public short HeadEndLeaderThickness { get; set; }
            public short HeadEndLeaderWidth { get; set; }
            public short HeadEndLeaderLength { get; set; }
            public short HeadEndLeaderWeldPointPosition { get; set; }
            public short HeadEndLeaderWeldPointDist { get; set; }
            public short TailEndLeaderAttached { get; set; }
            public short TailEndLeaderSteelGrade { get; set; }
            public short TailEndLeaderThickness { get; set; }
            public short TailEndLeaderWidth { get; set; }
            public short TailEndLeaderLength { get; set; }
            public short TailEndLeaderWeldPointPosition { get; set; }
            public short TailEndLeaderWeldPointDist { get; set; }
            public short SleeveInstalled { get; set; }
            public short SleeveThickness { get; set; }
            public short SleeveWidth { get; set; }
            public short PaperInstalled { get; set; }
            public short SleevePaperCode { get; set; }
            public short SleevePaperType { get; set; }
            public short UnitTension { get; set; }
            public short PassNumberForCoilHeadGrinding { get; set; }
            public short PassNumberForCoilCenterGrinding { get; set; }
            public short PassNumberForCoilTailGrinding { get; set; }
            public short LineSpeed1Head { get; set; }
            public string No1GrAbBeltKind1Head { get; set; }
            public short No1GrAbBeltRoughness1Head { get; set; }
            public short No1GrAbBeltRotatingDirection1Head { get; set; }
            public short No1GrGrinderMotorCurrentSet1Head { get; set; }
            public short No1GrAbBeltSpeed1Head { get; set; }
            public string No2GrAbBeltKind1Head { get; set; }
            public short No2GrAbBeltRoughness1Head { get; set; }
            public short No2GrAbBeltRotatingDirection1Head { get; set; }
            public short No2GrGrinderMotorCurrentSet1Head { get; set; }
            public short No2GrAbBeltSpeed1Head { get; set; }
            public string No3GrAbBeltKind1Head { get; set; }
            public short No3GrAbBeltRoughness1Head { get; set; }
            public short No3GrAbBeltRotatingDirection1Head { get; set; }
            public short No3GrGrinderMotorCurrentSet1Head { get; set; }
            public string No4GrAbBeltKind1Head { get; set; }
            public short No4GrAbBeltRoughness1Head { get; set; }
            public short No4GrAbBeltRotatingDirection1Head { get; set; }
            public short No4GrGrinderMotorCurrentSet1Head { get; set; }
            public string No5GrAbBeltKind1Head { get; set; }
            public short No5GrAbBeltRoughness1Head { get; set; }
            public short No5GrAbBeltRotatingDirection1Head { get; set; }
            public short No5GrGrinderMotorCurrentSet1Head { get; set; }
            public string No6GrAbBeltKind1Head { get; set; }
            public short No6GrAbBeltRoughness1Head { get; set; }
            public short No6GrAbBeltRotatingDirection1Head { get; set; }
            public short No6GrGrinderMotorCurrentSet1Head { get; set; }
            public short LineSpeed1Center { get; set; }
            public string No1GrAbBeltKind1Center { get; set; }
            public short No1GrAbBeltRoughness1Center { get; set; }
            public short No1GrAbBeltRotatingDirection1Center { get; set; }
            public short No1GrGrinderMotorCurrentSet1Center { get; set; }
            public short No1GrAbBeltSpeed1Center { get; set; }
            public string No2GrAbBeltKind1Center { get; set; }
            public short No2GrAbBeltRoughness1Center { get; set; }
            public short No2GrAbBeltRotatingDirection1Center { get; set; }
            public short No2GrGrinderMotorCurrentSet1Center { get; set; }
            public short No2GrAbBeltSpeed1Center { get; set; }
            public string No3GrAbBeltKind1Center { get; set; }
            public short No3GrAbBeltRoughness1Center { get; set; }
            public short No3GrAbBeltRotatingDirection1Center { get; set; }
            public short No3GrGrinderMotorCurrentSet1Center { get; set; }
            public string No4GrAbBeltKind1Center { get; set; }
            public short No4GrAbBeltRoughness1Center { get; set; }
            public short No4GrAbBeltRotatingDirection1Center { get; set; }
            public short No4GrGrinderMotorCurrentSet1Center { get; set; }
            public string No5GrAbBeltKind1Center { get; set; }
            public short No5GrAbBeltRoughness1Center { get; set; }
            public short No5GrAbBeltRotatingDirection1Center { get; set; }
            public short No5GrGrinderMotorCurrentSet1Center { get; set; }
            public string No6GrAbBeltKind1Center { get; set; }
            public short No6GrAbBeltRoughness1Center { get; set; }
            public short No6GrAbBeltRotatingDirection1Center { get; set; }
            public short No6GrGrinderMotorCurrentSet1Center { get; set; }
            public short LineSpeed1Tail { get; set; }
            public string No1GrAbBeltKind1Tail { get; set; }
            public short No1GrAbBeltRoughness1Tail { get; set; }
            public short No1GrAbBeltRotatingDirection1Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet1Tail { get; set; }
            public short No1GrAbBeltSpeed1Tail { get; set; }
            public string No2GrAbBeltKind1Tail { get; set; }
            public short No2GrAbBeltRoughness1Tail { get; set; }
            public short No2GrAbBeltRotatingDirection1Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet1Tail { get; set; }
            public short No2GrAbBeltSpeed1Tail { get; set; }
            public string No3GrAbBeltKind1Tail { get; set; }
            public short No3GrAbBeltRoughness1Tail { get; set; }
            public short No3GrAbBeltRotatingDirection1Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet1Tail { get; set; }
            public string No4GrAbBeltKind1Tail { get; set; }
            public short No4GrAbBeltRoughness1Tail { get; set; }
            public short No4GrAbBeltRotatingDirection1Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet1Tail { get; set; }
            public string No5GrAbBeltKind1Tail { get; set; }
            public short No5GrAbBeltRoughness1Tail { get; set; }
            public short No5GrAbBeltRotatingDirection1Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet1Tail { get; set; }
            public string No6GrAbBeltKind1Tail { get; set; }
            public short No6GrAbBeltRoughness1Tail { get; set; }
            public short No6GrAbBeltRotatingDirection1Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet1Tail { get; set; }
            public short LineSpeed2Head { get; set; }
            public string No1GrAbBeltKind2Head { get; set; }
            public short No1GrAbBeltRoughness2Head { get; set; }
            public short No1GrAbBeltRotatingDirection2Head { get; set; }
            public short No1GrGrinderMotorCurrentSet2Head { get; set; }
            public short No1GrAbBeltSpeed2Head { get; set; }
            public string No2GrAbBeltKind2Head { get; set; }
            public short No2GrAbBeltRoughness2Head { get; set; }
            public short No2GrAbBeltRotatingDirection2Head { get; set; }
            public short No2GrGrinderMotorCurrentSet2Head { get; set; }
            public short No2GrAbBeltSpeed2Head { get; set; }
            public string No3GrAbBeltKind2Head { get; set; }
            public short No3GrAbBeltRoughness2Head { get; set; }
            public short No3GrAbBeltRotatingDirection2Head { get; set; }
            public short No3GrGrinderMotorCurrentSet2Head { get; set; }
            public string No4GrAbBeltKind2Head { get; set; }
            public short No4GrAbBeltRoughness2Head { get; set; }
            public short No4GrAbBeltRotatingDirection2Head { get; set; }
            public short No4GrGrinderMotorCurrentSet2Head { get; set; }
            public string No5GrAbBeltKind2Head { get; set; }
            public short No5GrAbBeltRoughness2Head { get; set; }
            public short No5GrAbBeltRotatingDirection2Head { get; set; }
            public short No5GrGrinderMotorCurrentSet2Head { get; set; }
            public string No6GrAbBeltKind2Head { get; set; }
            public short No6GrAbBeltRoughness2Head { get; set; }
            public short No6GrAbBeltRotatingDirection2Head { get; set; }
            public short No6GrGrinderMotorCurrentSet2Head { get; set; }
            public short LineSpeed2Center { get; set; }
            public string No1GrAbBeltKind2Center { get; set; }
            public short No1GrAbBeltRoughness2Center { get; set; }
            public short No1GrAbBeltRotatingDirection2Center { get; set; }
            public short No1GrGrinderMotorCurrentSet2Center { get; set; }
            public short No1GrAbBeltSpeed2Center { get; set; }
            public string No2GrAbBeltKind2Center { get; set; }
            public short No2GrAbBeltRoughness2Center { get; set; }
            public short No2GrAbBeltRotatingDirection2Center { get; set; }
            public short No2GrGrinderMotorCurrentSet2Center { get; set; }
            public short No2GrAbBeltSpeed2Center { get; set; }
            public string No3GrAbBeltKind2Center { get; set; }
            public short No3GrAbBeltRoughness2Center { get; set; }
            public short No3GrAbBeltRotatingDirection2Center { get; set; }
            public short No3GrGrinderMotorCurrentSet2Center { get; set; }
            public string No4GrAbBeltKind2Center { get; set; }
            public short No4GrAbBeltRoughness2Center { get; set; }
            public short No4GrAbBeltRotatingDirection2Center { get; set; }
            public short No4GrGrinderMotorCurrentSet2Center { get; set; }
            public string No5GrAbBeltKind2Center { get; set; }
            public short No5GrAbBeltRoughness2Center { get; set; }
            public short No5GrAbBeltRotatingDirection2Center { get; set; }
            public short No5GrGrinderMotorCurrentSet2Center { get; set; }
            public string No6GrAbBeltKind2Center { get; set; }
            public short No6GrAbBeltRoughness2Center { get; set; }
            public short No6GrAbBeltRotatingDirection2Center { get; set; }
            public short No6GrGrinderMotorCurrentSet2Center { get; set; }
            public short LineSpeed2Tail { get; set; }
            public string No1GrAbBeltKind2Tail { get; set; }
            public short No1GrAbBeltRoughness2Tail { get; set; }
            public short No1GrAbBeltRotatingDirection2Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet2Tail { get; set; }
            public short No1GrAbBeltSpeed2Tail { get; set; }
            public string No2GrAbBeltKind2Tail { get; set; }
            public short No2GrAbBeltRoughness2Tail { get; set; }
            public short No2GrAbBeltRotatingDirection2Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet2Tail { get; set; }
            public short No2GrAbBeltSpeed2Tail { get; set; }
            public string No3GrAbBeltKind2Tail { get; set; }
            public short No3GrAbBeltRoughness2Tail { get; set; }
            public short No3GrAbBeltRotatingDirection2Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet2Tail { get; set; }
            public string No4GrAbBeltKind2Tail { get; set; }
            public short No4GrAbBeltRoughness2Tail { get; set; }
            public short No4GrAbBeltRotatingDirection2Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet2Tail { get; set; }
            public string No5GrAbBeltKind2Tail { get; set; }
            public short No5GrAbBeltRoughness2Tail { get; set; }
            public short No5GrAbBeltRotatingDirection2Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet2Tail { get; set; }
            public string No6GrAbBeltKind2Tail { get; set; }
            public short No6GrAbBeltRoughness2Tail { get; set; }
            public short No6GrAbBeltRotatingDirection2Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet2Tail { get; set; }
            public short LineSpeed3Head { get; set; }
            public string No1GrAbBeltKind3Head { get; set; }
            public short No1GrAbBeltRoughness3Head { get; set; }
            public short No1GrAbBeltRotatingDirection3Head { get; set; }
            public short No1GrGrinderMotorCurrentSet3Head { get; set; }
            public short No1GrAbBeltSpeed3Head { get; set; }
            public string No2GrAbBeltKind3Head { get; set; }
            public short No2GrAbBeltRoughness3Head { get; set; }
            public short No2GrAbBeltRotatingDirection3Head { get; set; }
            public short No2GrGrinderMotorCurrentSet3Head { get; set; }
            public short No2GrAbBeltSpeed3Head { get; set; }
            public string No3GrAbBeltKind3Head { get; set; }
            public short No3GrAbBeltRoughness3Head { get; set; }
            public short No3GrAbBeltRotatingDirection3Head { get; set; }
            public short No3GrGrinderMotorCurrentSet3Head { get; set; }
            public string No4GrAbBeltKind3Head { get; set; }
            public short No4GrAbBeltRoughness3Head { get; set; }
            public short No4GrAbBeltRotatingDirection3Head { get; set; }
            public short No4GrGrinderMotorCurrentSet3Head { get; set; }
            public string No5GrAbBeltKind3Head { get; set; }
            public short No5GrAbBeltRoughness3Head { get; set; }
            public short No5GrAbBeltRotatingDirection3Head { get; set; }
            public short No5GrGrinderMotorCurrentSet3Head { get; set; }
            public string No6GrAbBeltKind3Head { get; set; }
            public short No6GrAbBeltRoughness3Head { get; set; }
            public short No6GrAbBeltRotatingDirection3Head { get; set; }
            public short No6GrGrinderMotorCurrentSet3Head { get; set; }
            public short LineSpeed3Center { get; set; }
            public string No1GrAbBeltKind3Center { get; set; }
            public short No1GrAbBeltRoughness3Center { get; set; }
            public short No1GrAbBeltRotatingDirection3Center { get; set; }
            public short No1GrGrinderMotorCurrentSet3Center { get; set; }
            public short No1GrAbBeltSpeed3Center { get; set; }
            public string No2GrAbBeltKind3Center { get; set; }
            public short No2GrAbBeltRoughness3Center { get; set; }
            public short No2GrAbBeltRotatingDirection3Center { get; set; }
            public short No2GrGrinderMotorCurrentSet3Center { get; set; }
            public short No2GrAbBeltSpeed3Center { get; set; }
            public string No3GrAbBeltKind3Center { get; set; }
            public short No3GrAbBeltRoughness3Center { get; set; }
            public short No3GrAbBeltRotatingDirection3Center { get; set; }
            public short No3GrGrinderMotorCurrentSet3Center { get; set; }
            public string No4GrAbBeltKind3Center { get; set; }
            public short No4GrAbBeltRoughness3Center { get; set; }
            public short No4GrAbBeltRotatingDirection3Center { get; set; }
            public short No4GrGrinderMotorCurrentSet3Center { get; set; }
            public string No5GrAbBeltKind3Center { get; set; }
            public short No5GrAbBeltRoughness3Center { get; set; }
            public short No5GrAbBeltRotatingDirection3Center { get; set; }
            public short No5GrGrinderMotorCurrentSet3Center { get; set; }
            public string No6GrAbBeltKind3Center { get; set; }
            public short No6GrAbBeltRoughness3Center { get; set; }
            public short No6GrAbBeltRotatingDirection3Center { get; set; }
            public short No6GrGrinderMotorCurrentSet3Center { get; set; }
            public short LineSpeed3Tail { get; set; }
            public string No1GrAbBeltKind3Tail { get; set; }
            public short No1GrAbBeltRoughness3Tail { get; set; }
            public short No1GrAbBeltRotatingDirection3Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet3Tail { get; set; }
            public short No1GrAbBeltSpeed3Tail { get; set; }
            public string No2GrAbBeltKind3Tail { get; set; }
            public short No2GrAbBeltRoughness3Tail { get; set; }
            public short No2GrAbBeltRotatingDirection3Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet3Tail { get; set; }
            public short No2GrAbBeltSpeed3Tail { get; set; }
            public string No3GrAbBeltKind3Tail { get; set; }
            public short No3GrAbBeltRoughness3Tail { get; set; }
            public short No3GrAbBeltRotatingDirection3Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet3Tail { get; set; }
            public string No4GrAbBeltKind3Tail { get; set; }
            public short No4GrAbBeltRoughness3Tail { get; set; }
            public short No4GrAbBeltRotatingDirection3Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet3Tail { get; set; }
            public string No5GrAbBeltKind3Tail { get; set; }
            public short No5GrAbBeltRoughness3Tail { get; set; }
            public short No5GrAbBeltRotatingDirection3Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet3Tail { get; set; }
            public string No6GrAbBeltKind3Tail { get; set; }
            public short No6GrAbBeltRoughness3Tail { get; set; }
            public short No6GrAbBeltRotatingDirection3Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet3Tail { get; set; }
            public short LineSpeed4Head { get; set; }
            public string No1GrAbBeltKind4Head { get; set; }
            public short No1GrAbBeltRoughness4Head { get; set; }
            public short No1GrAbBeltRotatingDirection4Head { get; set; }
            public short No1GrGrinderMotorCurrentSet4Head { get; set; }
            public short No1GrAbBeltSpeed4Head { get; set; }
            public string No2GrAbBeltKind4Head { get; set; }
            public short No2GrAbBeltRoughness4Head { get; set; }
            public short No2GrAbBeltRotatingDirection4Head { get; set; }
            public short No2GrGrinderMotorCurrentSet4Head { get; set; }
            public short No2GrAbBeltSpeed4Head { get; set; }
            public string No3GrAbBeltKind4Head { get; set; }
            public short No3GrAbBeltRoughness4Head { get; set; }
            public short No3GrAbBeltRotatingDirection4Head { get; set; }
            public short No3GrGrinderMotorCurrentSet4Head { get; set; }
            public string No4GrAbBeltKind4Head { get; set; }
            public short No4GrAbBeltRoughness4Head { get; set; }
            public short No4GrAbBeltRotatingDirection4Head { get; set; }
            public short No4GrGrinderMotorCurrentSet4Head { get; set; }
            public string No5GrAbBeltKind4Head { get; set; }
            public short No5GrAbBeltRoughness4Head { get; set; }
            public short No5GrAbBeltRotatingDirection4Head { get; set; }
            public short No5GrGrinderMotorCurrentSet4Head { get; set; }
            public string No6GrAbBeltKind4Head { get; set; }
            public short No6GrAbBeltRoughness4Head { get; set; }
            public short No6GrAbBeltRotatingDirection4Head { get; set; }
            public short No6GrGrinderMotorCurrentSet4Head { get; set; }
            public short LineSpeed4Center { get; set; }
            public string No1GrAbBeltKind4Center { get; set; }
            public short No1GrAbBeltRoughness4Center { get; set; }
            public short No1GrAbBeltRotatingDirection4Center { get; set; }
            public short No1GrGrinderMotorCurrentSet4Center { get; set; }
            public short No1GrAbBeltSpeed4Center { get; set; }
            public string No2GrAbBeltKind4Center { get; set; }
            public short No2GrAbBeltRoughness4Center { get; set; }
            public short No2GrAbBeltRotatingDirection4Center { get; set; }
            public short No2GrGrinderMotorCurrentSet4Center { get; set; }
            public short No2GrAbBeltSpeed4Center { get; set; }
            public string No3GrAbBeltKind4Center { get; set; }
            public short No3GrAbBeltRoughness4Center { get; set; }
            public short No3GrAbBeltRotatingDirection4Center { get; set; }
            public short No3GrGrinderMotorCurrentSet4Center { get; set; }
            public string No4GrAbBeltKind4Center { get; set; }
            public short No4GrAbBeltRoughness4Center { get; set; }
            public short No4GrAbBeltRotatingDirection4Center { get; set; }
            public short No4GrGrinderMotorCurrentSet4Center { get; set; }
            public string No5GrAbBeltKind4Center { get; set; }
            public short No5GrAbBeltRoughness4Center { get; set; }
            public short No5GrAbBeltRotatingDirection4Center { get; set; }
            public short No5GrGrinderMotorCurrentSet4Center { get; set; }
            public string No6GrAbBeltKind4Center { get; set; }
            public short No6GrAbBeltRoughness4Center { get; set; }
            public short No6GrAbBeltRotatingDirection4Center { get; set; }
            public short No6GrGrinderMotorCurrentSet4Center { get; set; }
            public short LineSpeed4Tail { get; set; }
            public string No1GrAbBeltKind4Tail { get; set; }
            public short No1GrAbBeltRoughness4Tail { get; set; }
            public short No1GrAbBeltRotatingDirection4Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet4Tail { get; set; }
            public short No1GrAbBeltSpeed4Tail { get; set; }
            public string No2GrAbBeltKind4Tail { get; set; }
            public short No2GrAbBeltRoughness4Tail { get; set; }
            public short No2GrAbBeltRotatingDirection4Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet4Tail { get; set; }
            public short No2GrAbBeltSpeed4Tail { get; set; }
            public string No3GrAbBeltKind4Tail { get; set; }
            public short No3GrAbBeltRoughness4Tail { get; set; }
            public short No3GrAbBeltRotatingDirection4Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet4Tail { get; set; }
            public string No4GrAbBeltKind4Tail { get; set; }
            public short No4GrAbBeltRoughness4Tail { get; set; }
            public short No4GrAbBeltRotatingDirection4Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet4Tail { get; set; }
            public string No5GrAbBeltKind4Tail { get; set; }
            public short No5GrAbBeltRoughness4Tail { get; set; }
            public short No5GrAbBeltRotatingDirection4Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet4Tail { get; set; }
            public string No6GrAbBeltKind4Tail { get; set; }
            public short No6GrAbBeltRoughness4Tail { get; set; }
            public short No6GrAbBeltRotatingDirection4Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet4Tail { get; set; }
            [PrimaryKey]
            public override DateTime CreateTime { get; set; }
        }

        public class L2L1_205 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public System.DateTime DateTime { get; set; }
            public short PresetPosition { get; set; }
            public short LineSpeed5Head { get; set; }
            public string No1GrAbBeltKind5Head { get; set; }
            public short No1GrAbBeltRoughness5Head { get; set; }
            public short No1GrAbBeltRotatingDirection5Head { get; set; }
            public short No1GrGrinderMotorCurrentSet5Head { get; set; }
            public short No1GrAbBeltSpeed5Head { get; set; }
            public string No2GrAbBeltKind5Head { get; set; }
            public short No2GrAbBeltRoughness5Head { get; set; }
            public short No2GrAbBeltRotatingDirection5Head { get; set; }
            public short No2GrGrinderMotorCurrentSet5Head { get; set; }
            public short No2GrAbBeltSpeed5Head { get; set; }
            public string No3GrAbBeltKind5Head { get; set; }
            public short No3GrAbBeltRoughness5Head { get; set; }
            public short No3GrAbBeltRotatingDirection5Head { get; set; }
            public short No3GrGrinderMotorCurrentSet5Head { get; set; }
            public string No4GrAbBeltKind5Head { get; set; }
            public short No4GrAbBeltRoughness5Head { get; set; }
            public short No4GrAbBeltRotatingDirection5Head { get; set; }
            public short No4GrGrinderMotorCurrentSet5Head { get; set; }
            public string No5GrAbBeltKind5Head { get; set; }
            public short No5GrAbBeltRoughness5Head { get; set; }
            public short No5GrAbBeltRotatingDirection5Head { get; set; }
            public short No5GrGrinderMotorCurrentSet5Head { get; set; }
            public string No6GrAbBeltKind5Head { get; set; }
            public short No6GrAbBeltRoughness5Head { get; set; }
            public short No6GrAbBeltRotatingDirection5Head { get; set; }
            public short No6GrGrinderMotorCurrentSet5Head { get; set; }
            public short LineSpeed5Center { get; set; }
            public string No1GrAbBeltKind5Center { get; set; }
            public short No1GrAbBeltRoughness5Center { get; set; }
            public short No1GrAbBeltRotatingDirection5Center { get; set; }
            public short No1GrGrinderMotorCurrentSet5Center { get; set; }
            public short No1GrAbBeltSpeed5Center { get; set; }
            public string No2GrAbBeltKind5Center { get; set; }
            public short No2GrAbBeltRoughness5Center { get; set; }
            public short No2GrAbBeltRotatingDirection5Center { get; set; }
            public short No2GrGrinderMotorCurrentSet5Center { get; set; }
            public short No2GrAbBeltSpeed5Center { get; set; }
            public string No3GrAbBeltKind5Center { get; set; }
            public short No3GrAbBeltRoughness5Center { get; set; }
            public short No3GrAbBeltRotatingDirection5Center { get; set; }
            public short No3GrGrinderMotorCurrentSet5Center { get; set; }
            public string No4GrAbBeltKind5Center { get; set; }
            public short No4GrAbBeltRoughness5Center { get; set; }
            public short No4GrAbBeltRotatingDirection5Center { get; set; }
            public short No4GrGrinderMotorCurrentSet5Center { get; set; }
            public string No5GrAbBeltKind5Center { get; set; }
            public short No5GrAbBeltRoughness5Center { get; set; }
            public short No5GrAbBeltRotatingDirection5Center { get; set; }
            public short No5GrGrinderMotorCurrentSet5Center { get; set; }
            public string No6GrAbBeltKind5Center { get; set; }
            public short No6GrAbBeltRoughness5Center { get; set; }
            public short No6GrAbBeltRotatingDirection5Center { get; set; }
            public short No6GrGrinderMotorCurrentSet5Center { get; set; }
            public short LineSpeed5Tail { get; set; }
            public string No1GrAbBeltKind5Tail { get; set; }
            public short No1GrAbBeltRoughness5Tail { get; set; }
            public short No1GrAbBeltRotatingDirection5Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet5Tail { get; set; }
            public short No1GrAbBeltSpeed5Tail { get; set; }
            public string No2GrAbBeltKind5Tail { get; set; }
            public short No2GrAbBeltRoughness5Tail { get; set; }
            public short No2GrAbBeltRotatingDirection5Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet5Tail { get; set; }
            public short No2GrAbBeltSpeed5Tail { get; set; }
            public string No3GrAbBeltKind5Tail { get; set; }
            public short No3GrAbBeltRoughness5Tail { get; set; }
            public short No3GrAbBeltRotatingDirection5Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet5Tail { get; set; }
            public string No4GrAbBeltKind5Tail { get; set; }
            public short No4GrAbBeltRoughness5Tail { get; set; }
            public short No4GrAbBeltRotatingDirection5Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet5Tail { get; set; }
            public string No5GrAbBeltKind5Tail { get; set; }
            public short No5GrAbBeltRoughness5Tail { get; set; }
            public short No5GrAbBeltRotatingDirection5Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet5Tail { get; set; }
            public string No6GrAbBeltKind5Tail { get; set; }
            public short No6GrAbBeltRoughness5Tail { get; set; }
            public short No6GrAbBeltRotatingDirection5Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet5Tail { get; set; }
            public short LineSpeed6Head { get; set; }
            public string No1GrAbBeltKind6Head { get; set; }
            public short No1GrAbBeltRoughness6Head { get; set; }
            public short No1GrAbBeltRotatingDirection6Head { get; set; }
            public short No1GrGrinderMotorCurrentSet6Head { get; set; }
            public short No1GrAbBeltSpeed6Head { get; set; }
            public string No2GrAbBeltKind6Head { get; set; }
            public short No2GrAbBeltRoughness6Head { get; set; }
            public short No2GrAbBeltRotatingDirection6Head { get; set; }
            public short No2GrGrinderMotorCurrentSet6Head { get; set; }
            public short No2GrAbBeltSpeed6Head { get; set; }
            public string No3GrAbBeltKind6Head { get; set; }
            public short No3GrAbBeltRoughness6Head { get; set; }
            public short No3GrAbBeltRotatingDirection6Head { get; set; }
            public short No3GrGrinderMotorCurrentSet6Head { get; set; }
            public string No4GrAbBeltKind6Head { get; set; }
            public short No4GrAbBeltRoughness6Head { get; set; }
            public short No4GrAbBeltRotatingDirection6Head { get; set; }
            public short No4GrGrinderMotorCurrentSet6Head { get; set; }
            public string No5GrAbBeltKind6Head { get; set; }
            public short No5GrAbBeltRoughness6Head { get; set; }
            public short No5GrAbBeltRotatingDirection6Head { get; set; }
            public short No5GrGrinderMotorCurrentSet6Head { get; set; }
            public string No6GrAbBeltKind6Head { get; set; }
            public short No6GrAbBeltRoughness6Head { get; set; }
            public short No6GrAbBeltRotatingDirection6Head { get; set; }
            public short No6GrGrinderMotorCurrentSet6Head { get; set; }
            public short LineSpeed6Center { get; set; }
            public string No1GrAbBeltKind6Center { get; set; }
            public short No1GrAbBeltRoughness6Center { get; set; }
            public short No1GrAbBeltRotatingDirection6Center { get; set; }
            public short No1GrGrinderMotorCurrentSet6Center { get; set; }
            public short No1GrAbBeltSpeed6Center { get; set; }
            public string No2GrAbBeltKind6Center { get; set; }
            public short No2GrAbBeltRoughness6Center { get; set; }
            public short No2GrAbBeltRotatingDirection6Center { get; set; }
            public short No2GrGrinderMotorCurrentSet6Center { get; set; }
            public short No2GrAbBeltSpeed6Center { get; set; }
            public string No3GrAbBeltKind6Center { get; set; }
            public short No3GrAbBeltRoughness6Center { get; set; }
            public short No3GrAbBeltRotatingDirection6Center { get; set; }
            public short No3GrGrinderMotorCurrentSet6Center { get; set; }
            public string No4GrAbBeltKind6Center { get; set; }
            public short No4GrAbBeltRoughness6Center { get; set; }
            public short No4GrAbBeltRotatingDirection6Center { get; set; }
            public short No4GrGrinderMotorCurrentSet6Center { get; set; }
            public string No5GrAbBeltKind6Center { get; set; }
            public short No5GrAbBeltRoughness6Center { get; set; }
            public short No5GrAbBeltRotatingDirection6Center { get; set; }
            public short No5GrGrinderMotorCurrentSet6Center { get; set; }
            public string No6GrAbBeltKind6Center { get; set; }
            public short No6GrAbBeltRoughness6Center { get; set; }
            public short No6GrAbBeltRotatingDirection6Center { get; set; }
            public short No6GrGrinderMotorCurrentSet6Center { get; set; }
            public short LineSpeed6Tail { get; set; }
            public string No1GrAbBeltKind6Tail { get; set; }
            public short No1GrAbBeltRoughness6Tail { get; set; }
            public short No1GrAbBeltRotatingDirection6Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet6Tail { get; set; }
            public short No1GrAbBeltSpeed6Tail { get; set; }
            public string No2GrAbBeltKind6Tail { get; set; }
            public short No2GrAbBeltRoughness6Tail { get; set; }
            public short No2GrAbBeltRotatingDirection6Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet6Tail { get; set; }
            public short No2GrAbBeltSpeed6Tail { get; set; }
            public string No3GrAbBeltKind6Tail { get; set; }
            public short No3GrAbBeltRoughness6Tail { get; set; }
            public short No3GrAbBeltRotatingDirection6Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet6Tail { get; set; }
            public string No4GrAbBeltKind6Tail { get; set; }
            public short No4GrAbBeltRoughness6Tail { get; set; }
            public short No4GrAbBeltRotatingDirection6Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet6Tail { get; set; }
            public string No5GrAbBeltKind6Tail { get; set; }
            public short No5GrAbBeltRoughness6Tail { get; set; }
            public short No5GrAbBeltRotatingDirection6Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet6Tail { get; set; }
            public string No6GrAbBeltKind6Tail { get; set; }
            public short No6GrAbBeltRoughness6Tail { get; set; }
            public short No6GrAbBeltRotatingDirection6Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet6Tail { get; set; }
            public short LineSpeed7Head { get; set; }
            public string No1GrAbBeltKind7Head { get; set; }
            public short No1GrAbBeltRoughness7Head { get; set; }
            public short No1GrAbBeltRotatingDirection7Head { get; set; }
            public short No1GrGrinderMotorCurrentSet7Head { get; set; }
            public short No1GrAbBeltSpeed7Head { get; set; }
            public string No2GrAbBeltKind7Head { get; set; }
            public short No2GrAbBeltRoughness7Head { get; set; }
            public short No2GrAbBeltRotatingDirection7Head { get; set; }
            public short No2GrGrinderMotorCurrentSet7Head { get; set; }
            public short No2GrAbBeltSpeed7Head { get; set; }
            public string No3GrAbBeltKind7Head { get; set; }
            public short No3GrAbBeltRoughness7Head { get; set; }
            public short No3GrAbBeltRotatingDirection7Head { get; set; }
            public short No3GrGrinderMotorCurrentSet7Head { get; set; }
            public string No4GrAbBeltKind7Head { get; set; }
            public short No4GrAbBeltRoughness7Head { get; set; }
            public short No4GrAbBeltRotatingDirection7Head { get; set; }
            public short No4GrGrinderMotorCurrentSet7Head { get; set; }
            public string No5GrAbBeltKind7Head { get; set; }
            public short No5GrAbBeltRoughness7Head { get; set; }
            public short No5GrAbBeltRotatingDirection7Head { get; set; }
            public short No5GrGrinderMotorCurrentSet7Head { get; set; }
            public string No6GrAbBeltKind7Head { get; set; }
            public short No6GrAbBeltRoughness7Head { get; set; }
            public short No6GrAbBeltRotatingDirection7Head { get; set; }
            public short No6GrGrinderMotorCurrentSet7Head { get; set; }
            public short LineSpeed7Center { get; set; }
            public string No1GrAbBeltKind7Center { get; set; }
            public short No1GrAbBeltRoughness7Center { get; set; }
            public short No1GrAbBeltRotatingDirection7Center { get; set; }
            public short No1GrGrinderMotorCurrentSet7Center { get; set; }
            public short No1GrAbBeltSpeed7Center { get; set; }
            public string No2GrAbBeltKind7Center { get; set; }
            public short No2GrAbBeltRoughness7Center { get; set; }
            public short No2GrAbBeltRotatingDirection7Center { get; set; }
            public short No2GrGrinderMotorCurrentSet7Center { get; set; }
            public short No2GrAbBeltSpeed7Center { get; set; }
            public string No3GrAbBeltKind7Center { get; set; }
            public short No3GrAbBeltRoughness7Center { get; set; }
            public short No3GrAbBeltRotatingDirection7Center { get; set; }
            public short No3GrGrinderMotorCurrentSet7Center { get; set; }
            public string No4GrAbBeltKind7Center { get; set; }
            public short No4GrAbBeltRoughness7Center { get; set; }
            public short No4GrAbBeltRotatingDirection7Center { get; set; }
            public short No4GrGrinderMotorCurrentSet7Center { get; set; }
            public string No5GrAbBeltKind7Center { get; set; }
            public short No5GrAbBeltRoughness7Center { get; set; }
            public short No5GrAbBeltRotatingDirection7Center { get; set; }
            public short No5GrGrinderMotorCurrentSet7Center { get; set; }
            public string No6GrAbBeltKind7Center { get; set; }
            public short No6GrAbBeltRoughness7Center { get; set; }
            public short No6GrAbBeltRotatingDirection7Center { get; set; }
            public short No6GrGrinderMotorCurrentSet7Center { get; set; }
            public short LineSpeed7Tail { get; set; }
            public string No1GrAbBeltKind7Tail { get; set; }
            public short No1GrAbBeltRoughness7Tail { get; set; }
            public short No1GrAbBeltRotatingDirection7Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet7Tail { get; set; }
            public short No1GrAbBeltSpeed7Tail { get; set; }
            public string No2GrAbBeltKind7Tail { get; set; }
            public short No2GrAbBeltRoughness7Tail { get; set; }
            public short No2GrAbBeltRotatingDirection7Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet7Tail { get; set; }
            public short No2GrAbBeltSpeed7Tail { get; set; }
            public string No3GrAbBeltKind7Tail { get; set; }
            public short No3GrAbBeltRoughness7Tail { get; set; }
            public short No3GrAbBeltRotatingDirection7Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet7Tail { get; set; }
            public string No4GrAbBeltKind7Tail { get; set; }
            public short No4GrAbBeltRoughness7Tail { get; set; }
            public short No4GrAbBeltRotatingDirection7Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet7Tail { get; set; }
            public string No5GrAbBeltKind7Tail { get; set; }
            public short No5GrAbBeltRoughness7Tail { get; set; }
            public short No5GrAbBeltRotatingDirection7Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet7Tail { get; set; }
            public string No6GrAbBeltKind7Tail { get; set; }
            public short No6GrAbBeltRoughness7Tail { get; set; }
            public short No6GrAbBeltRotatingDirection7Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet7Tail { get; set; }
            public short LineSpeed8Head { get; set; }
            public string No1GrAbBeltKind8Head { get; set; }
            public short No1GrAbBeltRoughness8Head { get; set; }
            public short No1GrAbBeltRotatingDirection8Head { get; set; }
            public short No1GrGrinderMotorCurrentSet8Head { get; set; }
            public short No1GrAbBeltSpeed8Head { get; set; }
            public string No2GrAbBeltKind8Head { get; set; }
            public short No2GrAbBeltRoughness8Head { get; set; }
            public short No2GrAbBeltRotatingDirection8Head { get; set; }
            public short No2GrGrinderMotorCurrentSet8Head { get; set; }
            public short No2GrAbBeltSpeed8Head { get; set; }
            public string No3GrAbBeltKind8Head { get; set; }
            public short No3GrAbBeltRoughness8Head { get; set; }
            public short No3GrAbBeltRotatingDirection8Head { get; set; }
            public short No3GrGrinderMotorCurrentSet8Head { get; set; }
            public string No4GrAbBeltKind8Head { get; set; }
            public short No4GrAbBeltRoughness8Head { get; set; }
            public short No4GrAbBeltRotatingDirection8Head { get; set; }
            public short No4GrGrinderMotorCurrentSet8Head { get; set; }
            public string No5GrAbBeltKind8Head { get; set; }
            public short No5GrAbBeltRoughness8Head { get; set; }
            public short No5GrAbBeltRotatingDirection8Head { get; set; }
            public short No5GrGrinderMotorCurrentSet8Head { get; set; }
            public string No6GrAbBeltKind8Head { get; set; }
            public short No6GrAbBeltRoughness8Head { get; set; }
            public short No6GrAbBeltRotatingDirection8Head { get; set; }
            public short No6GrGrinderMotorCurrentSet8Head { get; set; }
            public short LineSpeed8Center { get; set; }
            public string No1GrAbBeltKind8Center { get; set; }
            public short No1GrAbBeltRoughness8Center { get; set; }
            public short No1GrAbBeltRotatingDirection8Center { get; set; }
            public short No1GrGrinderMotorCurrentSet8Center { get; set; }
            public short No1GrAbBeltSpeed8Center { get; set; }
            public string No2GrAbBeltKind8Center { get; set; }
            public short No2GrAbBeltRoughness8Center { get; set; }
            public short No2GrAbBeltRotatingDirection8Center { get; set; }
            public short No2GrGrinderMotorCurrentSet8Center { get; set; }
            public short No2GrAbBeltSpeed8Center { get; set; }
            public string No3GrAbBeltKind8Center { get; set; }
            public short No3GrAbBeltRoughness8Center { get; set; }
            public short No3GrAbBeltRotatingDirection8Center { get; set; }
            public short No3GrGrinderMotorCurrentSet8Center { get; set; }
            public string No4GrAbBeltKind8Center { get; set; }
            public short No4GrAbBeltRoughness8Center { get; set; }
            public short No4GrAbBeltRotatingDirection8Center { get; set; }
            public short No4GrGrinderMotorCurrentSet8Center { get; set; }
            public string No5GrAbBeltKind8Center { get; set; }
            public short No5GrAbBeltRoughness8Center { get; set; }
            public short No5GrAbBeltRotatingDirection8Center { get; set; }
            public short No5GrGrinderMotorCurrentSet8Center { get; set; }
            public string No6GrAbBeltKind8Center { get; set; }
            public short No6GrAbBeltRoughness8Center { get; set; }
            public short No6GrAbBeltRotatingDirection8Center { get; set; }
            public short No6GrGrinderMotorCurrentSet8Center { get; set; }
            public short LineSpeed8Tail { get; set; }
            public string No1GrAbBeltKind8Tail { get; set; }
            public short No1GrAbBeltRoughness8Tail { get; set; }
            public short No1GrAbBeltRotatingDirection8Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet8Tail { get; set; }
            public short No1GrAbBeltSpeed8Tail { get; set; }
            public string No2GrAbBeltKind8Tail { get; set; }
            public short No2GrAbBeltRoughness8Tail { get; set; }
            public short No2GrAbBeltRotatingDirection8Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet8Tail { get; set; }
            public short No2GrAbBeltSpeed8Tail { get; set; }
            public string No3GrAbBeltKind8Tail { get; set; }
            public short No3GrAbBeltRoughness8Tail { get; set; }
            public short No3GrAbBeltRotatingDirection8Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet8Tail { get; set; }
            public string No4GrAbBeltKind8Tail { get; set; }
            public short No4GrAbBeltRoughness8Tail { get; set; }
            public short No4GrAbBeltRotatingDirection8Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet8Tail { get; set; }
            public string No5GrAbBeltKind8Tail { get; set; }
            public short No5GrAbBeltRoughness8Tail { get; set; }
            public short No5GrAbBeltRotatingDirection8Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet8Tail { get; set; }
            public string No6GrAbBeltKind8Tail { get; set; }
            public short No6GrAbBeltRoughness8Tail { get; set; }
            public short No6GrAbBeltRotatingDirection8Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet8Tail { get; set; }
            public short LineSpeed9Head { get; set; }
            public string No1GrAbBeltKind9Head { get; set; }
            public short No1GrAbBeltRoughness9Head { get; set; }
            public short No1GrAbBeltRotatingDirection9Head { get; set; }
            public short No1GrGrinderMotorCurrentSet9Head { get; set; }
            public short No1GrAbBeltSpeed9Head { get; set; }
            public string No2GrAbBeltKind9Head { get; set; }
            public short No2GrAbBeltRoughness9Head { get; set; }
            public short No2GrAbBeltRotatingDirection9Head { get; set; }
            public short No2GrGrinderMotorCurrentSet9Head { get; set; }
            public short No2GrAbBeltSpeed9Head { get; set; }
            public string No3GrAbBeltKind9Head { get; set; }
            public short No3GrAbBeltRoughness9Head { get; set; }
            public short No3GrAbBeltRotatingDirection9Head { get; set; }
            public short No3GrGrinderMotorCurrentSet9Head { get; set; }
            public string No4GrAbBeltKind9Head { get; set; }
            public short No4GrAbBeltRoughness9Head { get; set; }
            public short No4GrAbBeltRotatingDirection9Head { get; set; }
            public short No4GrGrinderMotorCurrentSet9Head { get; set; }
            public string No5GrAbBeltKind9Head { get; set; }
            public short No5GrAbBeltRoughness9Head { get; set; }
            public short No5GrAbBeltRotatingDirection9Head { get; set; }
            public short No5GrGrinderMotorCurrentSet9Head { get; set; }
            public string No6GrAbBeltKind9Head { get; set; }
            public short No6GrAbBeltRoughness9Head { get; set; }
            public short No6GrAbBeltRotatingDirection9Head { get; set; }
            public short No6GrGrinderMotorCurrentSet9Head { get; set; }
            public short LineSpeed9Center { get; set; }
            public string No1GrAbBeltKind9Center { get; set; }
            public short No1GrAbBeltRoughness9Center { get; set; }
            public short No1GrAbBeltRotatingDirection9Center { get; set; }
            public short No1GrGrinderMotorCurrentSet9Center { get; set; }
            public short No1GrAbBeltSpeed9Center { get; set; }
            public string No2GrAbBeltKind9Center { get; set; }
            public short No2GrAbBeltRoughness9Center { get; set; }
            public short No2GrAbBeltRotatingDirection9Center { get; set; }
            public short No2GrGrinderMotorCurrentSet9Center { get; set; }
            public short No2GrAbBeltSpeed9Center { get; set; }
            public string No3GrAbBeltKind9Center { get; set; }
            public short No3GrAbBeltRoughness9Center { get; set; }
            public short No3GrAbBeltRotatingDirection9Center { get; set; }
            public short No3GrGrinderMotorCurrentSet9Center { get; set; }
            public string No4GrAbBeltKind9Center { get; set; }
            public short No4GrAbBeltRoughness9Center { get; set; }
            public short No4GrAbBeltRotatingDirection9Center { get; set; }
            public short No4GrGrinderMotorCurrentSet9Center { get; set; }
            public string No5GrAbBeltKind9Center { get; set; }
            public short No5GrAbBeltRoughness9Center { get; set; }
            public short No5GrAbBeltRotatingDirection9Center { get; set; }
            public short No5GrGrinderMotorCurrentSet9Center { get; set; }
            public string No6GrAbBeltKind9Center { get; set; }
            public short No6GrAbBeltRoughness9Center { get; set; }
            public short No6GrAbBeltRotatingDirection9Center { get; set; }
            public short No6GrGrinderMotorCurrentSet9Center { get; set; }
            public short LineSpeed9Tail { get; set; }
            public string No1GrAbBeltKind9Tail { get; set; }
            public short No1GrAbBeltRoughness9Tail { get; set; }
            public short No1GrAbBeltRotatingDirection9Tail { get; set; }
            public short No1GrGrinderMotorCurrentSet9Tail { get; set; }
            public short No1GrAbBeltSpeed9Tail { get; set; }
            public string No2GrAbBeltKind9Tail { get; set; }
            public short No2GrAbBeltRoughness9Tail { get; set; }
            public short No2GrAbBeltRotatingDirection9Tail { get; set; }
            public short No2GrGrinderMotorCurrentSet9Tail { get; set; }
            public short No2GrAbBeltSpeed9Tail { get; set; }
            public string No3GrAbBeltKind9Tail { get; set; }
            public short No3GrAbBeltRoughness9Tail { get; set; }
            public short No3GrAbBeltRotatingDirection9Tail { get; set; }
            public short No3GrGrinderMotorCurrentSet9Tail { get; set; }
            public string No4GrAbBeltKind9Tail { get; set; }
            public short No4GrAbBeltRoughness9Tail { get; set; }
            public short No4GrAbBeltRotatingDirection9Tail { get; set; }
            public short No4GrGrinderMotorCurrentSet9Tail { get; set; }
            public string No5GrAbBeltKind9Tail { get; set; }
            public short No5GrAbBeltRoughness9Tail { get; set; }
            public short No5GrAbBeltRotatingDirection9Tail { get; set; }
            public short No5GrGrinderMotorCurrentSet9Tail { get; set; }
            public string No6GrAbBeltKind9Tail { get; set; }
            public short No6GrAbBeltRoughness9Tail { get; set; }
            public short No6GrAbBeltRotatingDirection9Tail { get; set; }
            public short No6GrGrinderMotorCurrentSet9Tail { get; set; }
            //public string DefectCode_1 { get; set; }
            //public string DefectOrigin_1 { get; set; }
            //public string Sid_1 { get; set; }
            //public string DefectPosWidthDirection_1 { get; set; }
            //public int DefectPosLengthStartDirection_1 { get; set; }
            //public int DefectPosLengthEndDirection_1 { get; set; }
            //public string DefectLevel_1 { get; set; }
            //public int DefectPercent_1 { get; set; }
            //public string DefectQualityGrade_1 { get; set; }
            //public string DefectCode_2 { get; set; }
            //public string DefectOrigin_2 { get; set; }
            //public string Sid_2 { get; set; }
            //public string DefectPosWidthDirection_2 { get; set; }
            //public int DefectPosLengthStartDirection_2 { get; set; }
            //public int DefectPosLengthEndDirection_2 { get; set; }
            //public string DefectLevel_2 { get; set; }
            //public int DefectPercent_2 { get; set; }
            //public string DefectQualityGrade_2 { get; set; }
            //public string DefectCode_3 { get; set; }
            //public string DefectOrigin_3 { get; set; }
            //public string Sid_3 { get; set; }
            //public string DefectPosWidthDirection_3 { get; set; }
            //public int DefectPosLengthStartDirection_3 { get; set; }
            //public int DefectPosLengthEndDirection_3 { get; set; }
            //public string DefectLevel_3 { get; set; }
            //public int DefectPercent_3 { get; set; }
            //public string DefectQualityGrade_3 { get; set; }
            //public string DefectCode_4 { get; set; }
            //public string DefectOrigin_4 { get; set; }
            //public string Sid_4 { get; set; }
            //public string DefectPosWidthDirection_4 { get; set; }
            //public int DefectPosLengthStartDirection_4 { get; set; }
            //public int DefectPosLengthEndDirection_4 { get; set; }
            //public string DefectLevel_4 { get; set; }
            //public int DefectPercent_4 { get; set; }
            //public string DefectQualityGrade_4 { get; set; }
            //public string DefectCode_5 { get; set; }
            //public string DefectOrigin_5 { get; set; }
            //public string Sid_5 { get; set; }
            //public string DefectPosWidthDirection_5 { get; set; }
            //public int DefectPosLengthStartDirection_5 { get; set; }
            //public int DefectPosLengthEndDirection_5 { get; set; }
            //public string DefectLevel_5 { get; set; }
            //public int DefectPercent_5 { get; set; }
            //public string DefectQualityGrade_5 { get; set; }
            //public string DefectCode_6 { get; set; }
            //public string DefectOrigin_6 { get; set; }
            //public string Sid_6 { get; set; }
            //public string DefectPosWidthDirection_6 { get; set; }
            //public int DefectPosLengthStartDirection_6 { get; set; }
            //public int DefectPosLengthEndDirection_6 { get; set; }
            //public string DefectLevel_6 { get; set; }
            //public int DefectPercent_6 { get; set; }
            //public string DefectQualityGrade_6 { get; set; }
            //public string DefectCode_7 { get; set; }
            //public string DefectOrigin_7 { get; set; }
            //public string Sid_7 { get; set; }
            //public string DefectPosWidthDirection_7 { get; set; }
            //public int DefectPosLengthStartDirection_7 { get; set; }
            //public int DefectPosLengthEndDirection_7 { get; set; }
            //public string DefectLevel_7 { get; set; }
            //public int DefectPercent_7 { get; set; }
            //public string DefectQualityGrade_7 { get; set; }
            //public string DefectCode_8 { get; set; }
            //public string DefectOrigin_8 { get; set; }
            //public string Sid_8 { get; set; }
            //public string DefectPosWidthDirection_8 { get; set; }
            //public int DefectPosLengthStartDirection_8 { get; set; }
            //public int DefectPosLengthEndDirection_8 { get; set; }
            //public string DefectLevel_8 { get; set; }
            //public int DefectPercent_8 { get; set; }
            //public string DefectQualityGrade_8 { get; set; }
            //public string DefectCode_9 { get; set; }
            //public string DefectOrigin_9 { get; set; }
            //public string Sid_9 { get; set; }
            //public string DefectPosWidthDirection_9 { get; set; }
            //public int DefectPosLengthStartDirection_9 { get; set; }
            //public int DefectPosLengthEndDirection_9 { get; set; }
            //public string DefectLevel_9 { get; set; }
            //public int DefectPercent_9 { get; set; }
            //public string DefectQualityGrade_9 { get; set; }
            //public string DefectCode_10 { get; set; }
            //public string DefectOrigin_10 { get; set; }
            //public string Sid_10 { get; set; }
            //public string DefectPosWidthDirection_10 { get; set; }
            //public int DefectPosLengthStartDirection_10 { get; set; }
            //public int DefectPosLengthEndDirection_10 { get; set; }
            //public string DefectLevel_10 { get; set; }
            //public int DefectPercent_10 { get; set; }
            //public string DefectQualityGrade_10 { get; set; }

            public int Defect_Flag { get; set; }
            [PrimaryKey]
            public override DateTime CreateTime { get; set; }
        }

        public class L2L1_206 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public DateTime DateTime { get; set; }
            public string ABbeltID { get; set; }
            public string ABbeltkind { get; set; }
            public short ABbeltroughness { get; set; }
            public float ABBeltAccGriBeltLength { get; set; }
            public float ABBeltAccGriStLength { get; set; } 
            public short BeltExistFlag { get; set; }

            [PrimaryKey]
            public override DateTime CreateTime { get; set; }
        }

        public class L2L1_207 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public DateTime DateTime { get; set; }
            public override DateTime CreateTime { get; set; }
        }
        public class L2L1_208 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public System.DateTime DateTime { get; set; }
            public override DateTime CreateTime { get; set; }
        }

        public class L2L1_209 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public System.DateTime DateTime { get; set; }
            public short CoilIDConfirmResult { get; set; }
            public override DateTime CreateTime { get; set; }
        }

        public class L2L1_210 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public DateTime DateTime { get; set; }
            public short DeleltePosition { get; set; }
            public string CoilId { get; set; }
            public override DateTime CreateTime { get; set; }
        }

        public class L2L1_211 : BaseRepositoryModel
        {
            public short MessageLength { get; set; }
            public short MessageId { get; set; }
            public int Date { get; set; }
            public int Time { get; set; }
            public DateTime DateTime { get; set; }
            public short ModifyPosition { get; set; }
            public string CoilId { get; set; }
            public override DateTime CreateTime { get; set; }
        }

    }
}
